[package]
name = "skimmer-cli"
description = "skimmer daemon and CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "skimmer"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
serde_json = { workspace = true }
skimmer-decode = { workspace = true }
skimmer-engine = { workspace = true }
skimmer-input = { workspace = true }
skimmer-testkit = { workspace = true }

[dev-dependencies]
coppa-audio = { workspace = true }
serde_json = { workspace = true }
skimmer-testkit = { workspace = true }
tempfile = { workspace = true }
