//! PFB prototype lowpass: Kaiser-windowed sinc. SPEC §1.2, §10.1.
//! All math in f64; coefficients stored as f32. Generated once at startup.

/// SPEC §1.2: beta = 0.1102 * (A - 8.7) with A = 80 dB.
pub const KAISER_BETA: f64 = 7.857;
/// SPEC §1.2: L = 8 taps per branch.
pub const TAPS_PER_BRANCH: usize = 8;

/// Modified Bessel function of the first kind, order zero (series expansion).
pub(crate) fn bessel_i0(x: f64) -> f64 {
    let mut sum = 1.0f64;
    let mut term = 1.0f64;
    let half = x / 2.0;
    let mut k = 1.0f64;
    loop {
        term *= (half / k) * (half / k);
        sum += term;
        if term < sum * 1e-16 {
            return sum;
        }
        k += 1.0;
    }
}

fn sinc(x: f64) -> f64 {
    if x.abs() < 1e-12 {
        1.0
    } else {
        let px = std::f64::consts::PI * x;
        px.sin() / px
    }
}

/// Design the length-L·N prototype. Cutoff f_c = Δ/2 makes the sinc argument
/// (i - center)/N, so the design depends only on N and L, not fs. SPEC §1.2.
pub fn design_prototype(n_channels: usize, taps_per_branch: usize) -> Vec<f32> {
    let len = n_channels * taps_per_branch;
    let center = (len - 1) as f64 / 2.0;
    let mut h = vec![0.0f64; len];
    let i0_beta = bessel_i0(KAISER_BETA);
    let mut sum = 0.0f64;
    for (i, tap) in h.iter_mut().enumerate() {
        let x = (i as f64 - center) / n_channels as f64; // = 2*f_c*(i-c)/fs
        let t = 2.0 * i as f64 / (len - 1) as f64 - 1.0; // [-1, 1]
        let w = bessel_i0(KAISER_BETA * (1.0 - t * t).sqrt()) / i0_beta;
        *tap = sinc(x) * w;
        sum += *tap;
    }
    // Unity DC gain per channel (SPEC §1.2).
    h.iter().map(|&v| (v / sum) as f32).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// |H(f)| in dB at frequency f (Hz) for an fs/N channel grid.
    /// Direct DTFT — slow but exact; test-only.
    fn response_db(h: &[f32], f_hz: f64, fs: f64) -> f64 {
        let (mut re, mut im) = (0.0f64, 0.0f64);
        for (i, &tap) in h.iter().enumerate() {
            let phi = -2.0 * std::f64::consts::PI * f_hz * i as f64 / fs;
            re += tap as f64 * phi.cos();
            im += tap as f64 * phi.sin();
        }
        10.0 * (re * re + im * im).log10()
    }

    #[test]
    fn beta_matches_spec_formula() {
        // SPEC §1.2: beta = 0.1102 * (80 - 8.7) = 7.857...
        assert!((KAISER_BETA - 0.1102 * (80.0 - 8.7)).abs() < 2e-3);
    }

    #[test]
    fn prototype_is_symmetric_and_unity_dc() {
        let h = design_prototype(1024, 8);
        assert_eq!(h.len(), 8192);
        for i in 0..h.len() / 2 {
            assert_eq!(h[i], h[h.len() - 1 - i], "tap {i} asymmetric");
        }
        let sum: f64 = h.iter().map(|&x| x as f64).sum();
        assert!((sum - 1.0).abs() < 1e-6, "DC gain {sum}");
    }

    #[test]
    fn minus_six_db_at_channel_edge() {
        // SPEC §1.2: f_c = 46.875 Hz is the -6 dB point (at fs = 96 kS/s, N = 1024).
        let h = design_prototype(1024, 8);
        let edge = response_db(&h, 46.875, 96_000.0);
        assert!((edge + 6.0).abs() < 0.6, "edge response {edge} dB");
    }

    #[test]
    fn stopband_at_least_78_db() {
        // SPEC §1.2: A = 80 dB target, stopband reached by ~107 Hz offset.
        // Assert >= 78 dB from 110 Hz out (2 dB design margin).
        let h = design_prototype(1024, 8);
        let mut worst = -300.0f64;
        let mut f = 110.0;
        while f < 48_000.0 {
            worst = worst.max(response_db(&h, f, 96_000.0));
            f += 23.0; // dense enough to catch sidelobe peaks (~11.7 Hz lobes)
        }
        assert!(worst <= -78.0, "worst stopband {worst} dB");
    }

    #[test]
    fn bessel_i0_reference_values() {
        // Abramowitz & Stegun: I0(0)=1, I0(1)=1.2660658, I0(5)=27.239871
        assert!((bessel_i0(0.0) - 1.0).abs() < 1e-12);
        assert!((bessel_i0(1.0) - 1.2660658).abs() < 1e-6);
        assert!((bessel_i0(5.0) - 27.239871).abs() < 1e-4);
    }

    #[test]
    #[ignore = "generator for the pinned snapshot below"]
    fn dump_reference_taps() {
        let h = design_prototype(1024, 8);
        let mid = h.len() / 2;
        println!("first:  {:?}", &h[0..4]);
        println!("middle: {:?}", &h[mid - 2..mid + 2]);
        println!("last:   {:?}", &h[h.len() - 4..]);
    }

    #[test]
    fn reference_taps_pinned() {
        // SPEC §1.2: pinned to 1e-7. Values generated by dump_reference_taps at
        // N=1024, L=8; any change here is a golden-vector-invalidating event.
        let h = design_prototype(1024, 8);
        let mid = h.len() / 2;
        let expect_first: [f32; 4] = [-3.1867653e-10, -9.634797e-10, -1.61826e-9, -2.2830688e-9];
        let expect_mid: [f32; 4] = [0.0009764334, 0.0009764369, 0.0009764369, 0.0009764334];
        let expect_last: [f32; 4] = [-2.2830688e-9, -1.61826e-9, -9.634797e-10, -3.1867653e-10];
        for (a, b) in h[0..4].iter().zip(expect_first) {
            assert!((a - b).abs() < 1e-7);
        }
        for (a, b) in h[mid - 2..mid + 2].iter().zip(expect_mid) {
            assert!((a - b).abs() < 1e-7);
        }
        for (a, b) in h[h.len() - 4..].iter().zip(expect_last) {
            assert!((a - b).abs() < 1e-7);
        }
    }
}
